import { LucideIcon } from 'lucide-react-native';
import { cssInterop } from 'nativewind';

function iconInterop(icon: LucideIcon) {
  cssInterop(icon, {
    className: {
      target: 'style',
      nativeStyleToProp: {
        color: true,
        width: 'size',
      },
    },
  });
}

import { 
  Home, 
  Search, 
  User, 
  Settings, 
  Heart, 
  Bell, 
  Plus, 
  Map as MapIcon,
  LogOut,
  ChevronRight,
  Star,
  Briefcase,
  MessageSquare,
  Filter,
  X,
  ChevronLeft,
  Share,
  ArrowRight,
  Wifi,
  ChefHat,
  Wind,
  Mountain,
  Car,
  Waves,
  Leaf,
  ShieldCheck,
  ShoppingBag,
  Bus,
  Sparkles,
  MessageCircle,
  Info,
  MoreHorizontal,
  Calendar,
  Eye,
  EyeOff,
  Globe,
  CheckCheck,
  Send,
  Tag,
  Zap,
  ThumbsUp,
  HelpCircle,
  Moon,
  Check,
  Clock,
  Flag,
  ShieldAlert,
  List,
  LayoutDashboard,
  Image,
  Trash2,
} from 'lucide-react-native';

const icons = [
  Home, Search, User, Settings, Heart, Bell, Plus, MapIcon, LogOut,
  ChevronRight, Star, Briefcase, MessageSquare, Filter, X, ChevronLeft,
  Share, ArrowRight, Wifi, ChefHat, Wind, Mountain, Car, Waves, Leaf,
  ShieldCheck, ShoppingBag, Bus, Sparkles, MessageCircle, Info, MoreHorizontal,
  Calendar, Eye, EyeOff, Globe, CheckCheck, Send, Tag, Zap, ThumbsUp,
  HelpCircle, Moon, Check, Clock, Flag, ShieldAlert, List, LayoutDashboard,
  Image, Trash2,
];

icons.forEach(iconInterop);

export { 
  Home, 
  Search, 
  User, 
  Settings, 
  Heart, 
  Bell, 
  Plus, 
  MapIcon as Map,
  LogOut,
  ChevronRight,
  Star,
  Briefcase,
  MessageSquare,
  Filter,
  X,
  ChevronLeft,
  Share,
  ArrowRight,
  Wifi,
  ChefHat,
  Wind,
  Mountain,
  Car,
  Waves,
  Leaf,
  ShieldCheck,
  ShoppingBag,
  Bus,
  Sparkles,
  MessageCircle,
  Info,
  MoreHorizontal,
  Calendar,
  Eye,
  EyeOff,
  Globe,
  CheckCheck,
  Send,
  Tag,
  Zap,
  ThumbsUp,
  HelpCircle,
  Moon,
  Check,
  Clock,
  Flag,
  ShieldAlert,
  List,
  LayoutDashboard,
  Image as ImageIcon,
  Trash2,
};
